//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.09 at 01:38:16 PM EDT 
//


package com.appiancorp.pluginexample;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.appiancorp.suiteapi.type.Hidden;


/**
 * <p>Java class for AppianMadLib complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppianMadLib">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noun1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noun2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noun3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adjective1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adjective2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="adjective3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
//This is how to deprecate a custom data type
@Hidden
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppianMadLib", namespace="http://appian.com/types/pluginexample", propOrder = {
    "title",
    "noun1",
    "noun2",
    "noun3",    
    "adjective1",
    "adjective2",
    "adjective3",
})
public class AppianMadLib {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String noun1;
    @XmlElement(required = true)
    protected String noun2;
    @XmlElement(required = true)
    protected String noun3;
    @XmlElement(required = true)
    protected String adjective1;
    @XmlElement(required = true)
    protected String adjective2;
    @XmlElement(required = true)
    protected String adjective3;


    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the noun1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoun1() {
        return noun1;
    }

    /**
     * Sets the value of the noun1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoun1(String value) {
        this.noun1 = value;
    }

    /**
     * Gets the value of the adjective1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjective1() {
        return adjective1;
    }

    /**
     * Sets the value of the adjective1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjective1(String value) {
        this.adjective1 = value;
    }

    /**
     * Gets the value of the noun2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoun2() {
        return noun2;
    }

    /**
     * Sets the value of the noun2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoun2(String value) {
        this.noun2 = value;
    }

    /**
     * Gets the value of the noun3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoun3() {
        return noun3;
    }

    /**
     * Sets the value of the noun3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoun3(String value) {
        this.noun3 = value;
    }

    /**
     * Gets the value of the adjective2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjective2() {
        return adjective2;
    }

    /**
     * Sets the value of the adjective2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjective2(String value) {
        this.adjective2 = value;
    }

    /**
     * Gets the value of the adjective3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjective3() {
        return adjective3;
    }

    /**
     * Sets the value of the adjective3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjective3(String value) {
        this.adjective3 = value;
    }


}
